### PR TITLE
Fix message type

### PR DESCRIPTION
**Pull request by tonyxiao**
Allow atom to correctly capture warning messages.

So this little indicator would work

image

### CODE REVIEW

**Comment by joefitzgerald** [comment]
Thanks for finding this! Can you also please file a bug at linter to make these values case insensitive?

**Comment by joefitzgerald** [comment]
Can you please fix the lint errors?

**Comment by tonyxiao** [comment]
Done and also filed an issue as well.

**Comment by joefitzgerald** [comment]
Thanks!

**Comment by keplersj** [comment]
That indicator is from nuclide, not linter

**Pull request merged**
